import{a as v,S as w,i as c}from"./assets/vendor-D9tHNiur.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const b="48926224-1e282cfdad2000a03e206ba59",E="https://pixabay.com/api/",R=40;async function m(r,s=1){try{return(await v.get(E,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:s,t:Date.now()}})).data}catch(o){throw console.error("Помилка запиту:",o),new Error("Не вдалося отримати дані з Pixabay.")}}const I=new w(".image-card a",{captionsData:"alt",captionDelay:250});function g(r,s,o=!1){if(o&&(s.innerHTML=""),r.length===0){s.innerHTML="<p>Sorry, there are no images matching your search query. Please try again!</p>";return}const n=r.map(e=>`
      <div class="image-card">
        <a href="${e.largeImageURL}" target="_blank">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="info">
          <p>Likes <span>${e.likes}</span></p>
          <p>Views <span>${e.views}</span></p>
          <p>Comments <span>${e.comments}</span></p>
          <p>Downloads <span>${e.downloads}</span></p>
        </div>
      </div>`).join("");s.insertAdjacentHTML("beforeend",n),I.refresh()}function y(r){r.classList.remove("hidden")}function f(r){r.classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const r=document.getElementById("search-form"),s=document.getElementById("search-input"),o=document.querySelector(".gallery"),n=document.getElementById("loader"),e=document.getElementById("load-more"),t=document.getElementById("end-message");if(!r||!s||!o||!n||!e||!t){console.error("Один або кілька елементів не знайдено в DOM!");return}let i="",p=1,u=0,d=0;r.addEventListener("submit",async h=>{if(h.preventDefault(),i=s.value.trim(),p=1,d=0,i===""){c.warning({message:"Поле пошуку не може бути порожнім!",position:"topRight"});return}o.innerHTML="",e.classList.add("hidden"),y(n);try{const l=await m(i,p),a=l.hits;if(u=l.totalHits,u===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),f(n);return}g(a,o,!0),d+=a.length,d<u?e.classList.remove("hidden"):(e.classList.add("hidden"),t.style.display="block")}catch{c.error({title:"❌ Помилка",message:"Не вдалося виконати запит. Спробуйте ще раз!",position:"topRight"})}finally{f(n)}}),e.addEventListener("click",async()=>{var h;p+=1,y(n);try{const a=(await m(i,p)).hits;if(a.length===0){c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),e.classList.add("hidden");return}g(a,o),d+=a.length;const L=((h=document.querySelector(".image-card"))==null?void 0:h.getBoundingClientRect().height)||0;window.scrollBy({top:L*2,behavior:"smooth"}),d>=u?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),e.classList.add("hidden")):e.classList.remove("hidden")}catch{c.error({title:"❌ Помилка",message:"Не вдалося завантажити більше зображень. Спробуйте ще раз!",position:"topRight"})}finally{f(n)}})});
//# sourceMappingURL=index.js.map
